requirements: require current pyOpenSSL
Fix exception in GitHub Actions:

    AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'